/*
  Script:      T_EWS_VERIFICATION_EXCEPTION
  Schema:	    ACCOUNT
  Author:      Jyoti Jerath
  Date:        11/19/2020
  Purpose:     New table to insert EWS Error Details
*****************************************************************************/

/*
NEW TABLE - T_EWS_VERIFICATION_EXCEPTION
*/
CREATE TABLE ACCOUNT.T_EWS_VERIFICATION_EXCEPTION(
EWS_VERIFICATION_EXCEPTION_ID NUMBER PRIMARY KEY, --EXCEPTION UNIQUE KEY  
IS_EWS_SYSTEM_ERROR CHAR(1), --1 IF EWS FAILED or 0 - NETWORK ISSUE 
ERROR_CD NUMBER, --ERROR_CODE
EXCEPTION_MESSAGE CLOB, --EXCEPTION MESSAGE
EWS_VERIFICATION_ID NUMBER
)
TABLESPACE ACCOUNT_D;

/*
COMMENTS ON NEW TABLE - T_EWS_VERIFICATION_EXCEPTION
*/
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION_EXCEPTION.EWS_VERIFICATION_EXCEPTION_ID IS 'EWS PAYMENT VALIDATION EXCEPTION UNIQUE KEY';
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION_EXCEPTION.ERROR_CD IS 'Error Code from EWS';
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION_EXCEPTION.IS_EWS_SYSTEM_ERROR IS '1- SYSTEM Error from EWS, 0 - Network issue';
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION_EXCEPTION.EXCEPTION_MESSAGE IS 'Network issue .NET Stack Trace';

/*
FOREIGN KEY CONSTRAINT ON NEW TABLE - T_EWS_VERIFICATION_EXCEPTION
*/
ALTER TABLE ACCOUNT.T_EWS_VERIFICATION_EXCEPTION ADD CONSTRAINT EWS_VER_ID_FK FOREIGN KEY (EWS_VERIFICATION_ID)
REFERENCES ACCOUNT.T_EWS_VERIFICATION(EWS_VERIFICATION_ID);

/*
SEQUENCE ON NEW TABLE - T_EWS_VERIFICATION_EXCEPTION
*/
CREATE SEQUENCE ACCOUNT.SEQ_EWS_VERIFICATION_EXCEPTION_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;