/*
  SCRIPT:      T_EWS_VERIFICATION_ACCOUNT.sql
  SCHEMA:	    ACCOUNT
  AUTHOR:      JYOTI JERATH
  DATE:        11/19/2020
  PURPOSE:     NEW TABLE
*****************************************************************************/


/*
SEQUENCE ON NEW TABLE - T_EWS_VERIFICATION_ACCOUNT
*/
CREATE SEQUENCE ACCOUNT.SEQ_EWS_VERIFICATION_ACCOUNT_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*
NEW TABLE - T_EWS_VERIFICATION_ACCOUNT
*/
CREATE TABLE ACCOUNT.T_EWS_VERIFICATION_ACCOUNT
(EWS_VERIFICATION_ACCOUNT_ID NUMBER PRIMARY KEY,  
EWS_VERIFICATION_ID NUMBER,   
CREDIT_ACCOUNT_ID NUMBER 
) TABLESPACE ACCOUNT_D;


/*
FOREIGN KEY CONSTRAINT ON NEW TABLE - T_EWS_VERIFICATION_ACCOUNT
*/
ALTER TABLE ACCOUNT.T_EWS_VERIFICATION_ACCOUNT ADD CONSTRAINT EWS_VERIFICATION_ID_FK FOREIGN KEY (EWS_VERIFICATION_ID)
REFERENCES ACCOUNT.T_EWS_VERIFICATION(EWS_VERIFICATION_ID);




