/*
  SCRIPT:      T_EWS_VERIFICATION.sql
  SCHEMA:	    ACCOUNT
  AUTHOR:      JYOTI JERATH
  DATE:        11/19/2020
  PURPOSE:     NEW TABLE TO INSERT EWS REQUEST & RESPONSE
*****************************************************************************/


/*
SEQUENCE ON NEW TABLE - T_EWS_VERIFICATION
*/
CREATE SEQUENCE ACCOUNT.SEQ_EWS_VERIFICATION_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*
NEW TABLE - T_EWS_VERIFICATION
*/
CREATE TABLE ACCOUNT.T_EWS_VERIFICATION
(
EWS_VERIFICATION_ID NUMBER PRIMARY KEY,   --UNIQUE ID
CLIENT_REC_ID varchar2(50) NOT NULL, --UUID for each request
CHANNEL_ID NUMBER, --Channel
ROUTING_NUMBER CLOB, --Routing Number
ACCOUNT_NUMBER CLOB, --Account Number
POST_DATE DATE DEFAULT SYSDATE NOT NULL, --POST DATE
TRANSACTION_ID NUMBER,  -- TRANSACTION ID IN RESPONSE FROM EWS
IS_SUCCESS CHAR(1) NOT NULL,  --1/0
EWS_RESPONSE CLOB --RESPONSE OBJECT
CONSTRAINT EWSRESPONSE_CHECK CHECK (EWS_RESPONSE IS JSON),
EWS_REQUEST CLOB --REQUEST OBJECT
CONSTRAINT EWSREQUEST_CHECK CHECK (EWS_REQUEST IS JSON)
) TABLESPACE ACCOUNT_D;


/*
FOREIGN KEY CONSTRAINT ON NEW TABLE - T_EWS_VERIFICATION
*/
ALTER TABLE ACCOUNT.T_EWS_VERIFICATION ADD CONSTRAINT CHANNEL_ID_FK FOREIGN KEY (CHANNEL_ID)
REFERENCES ACCOUNT.T_LU_EWS_VERIFICATION_CHANNEL(CHANNEL_ID);

/*
COMMENTS ON NEW TABLE - T_EWS_VERIFICATION
*/
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION.EWS_VERIFICATION_ID IS 'UNIQUE KEY';
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION.EWS_RESPONSE IS 'EWS RESPONSE OBJECT IN JSON FORMAT';
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION.EWS_REQUEST IS 'EWS REQUEST OBJECT IN JSON FORMAT';
COMMENT ON COLUMN ACCOUNT.T_EWS_VERIFICATION.CLIENT_REC_ID IS 'UUID for each request';

/*
INDEXES NEW TABLE - T_EWS_VERIFICATION
*/
CREATE INDEX IX_POST_DATE ON ACCOUNT.T_EWS_VERIFICATION(POST_DATE) TABLESPACE ACCOUNT_I;




