/*
  SCRIPT:      T_EWS_VERIFICATION_APPLICATION.sql
  SCHEMA:	    ACCOUNT
  AUTHOR:      JYOTI JERATH
  DATE:        11/19/2020
  PURPOSE:     NEW TABLE
*****************************************************************************/


/*
SEQUENCE ON NEW TABLE - T_EWS_VERIFICATION_APPLICATION
*/
CREATE SEQUENCE ACCOUNT.SEQ_EWS_VERIFICATION_APPLICATION_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*
NEW TABLE - T_EWS_VERIFICATION_APPLICATION
*/
CREATE TABLE ACCOUNT.T_EWS_VERIFICATION_APPLICATION
(EWS_VERIFICATION_APPLICATION_ID NUMBER PRIMARY KEY,  
EWS_VERIFICATION_ID NUMBER,   
APPLICATION_ID NUMBER
) TABLESPACE ACCOUNT_D;


/*
FOREIGN KEY CONSTRAINT ON NEW TABLE - T_EWS_VERIFICATION_APPLICATION
*/
ALTER TABLE ACCOUNT.T_EWS_VERIFICATION_APPLICATION ADD CONSTRAINT EWS_VER_APP_ID_FK FOREIGN KEY (EWS_VERIFICATION_ID)
REFERENCES ACCOUNT.T_EWS_VERIFICATION(EWS_VERIFICATION_ID);







