/*
  SCRIPT:      T_LU_EWS_VERIFICATION_CHANNEL.sql
  SCHEMA:	    ACCOUNT
  AUTHOR:      JYOTI JERATH
  DATE:        11/19/2020
  PURPOSE:     NEW LOOKUP TABLE FOR CHANNEL
*****************************************************************************/


/*
SEQUENCE ON NEW TABLE - T_LU_EWS_VERIFICATION_CHANNEL
*/
CREATE SEQUENCE ACCOUNT.SEQ_CHANNEL_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

/*
NEW TABLE - T_EWS_VERIFICATION
*/
CREATE TABLE ACCOUNT.T_LU_EWS_VERIFICATION_CHANNEL
(
CHANNEL_ID NUMBER PRIMARY KEY,   --UNIQUE ID
CHANNEL VARCHAR2(12) NOT NULL --Channel
) TABLESPACE ACCOUNT_D;


/*
INDEXES NEW TABLE - T_LU_EWS_VERIFICATION_CHANNEL
*/
CREATE UNIQUE INDEX IX_EWS_VERIFICATION_CHANNEL ON ACCOUNT.T_LU_EWS_VERIFICATION_CHANNEL(CHANNEL) TABLESPACE ACCOUNT_I;





