/*

  SCRIPT:      DEL_T_APPLICATION_CONFIGURATIONS_VAL.SQL
  SCHEMA:      IFLOW
  AUTHOR:      PABLO GOMEZ
  DATE:        1/5/2021
  PURPOSE:     VALIDATE DEL_T_RT_LOOKUP 

*/

DECLARE
    V_COUNT NUMBER;
    STR_ERR VARCHAR2(10000);
BEGIN
    STR_ERR   := NULL;
	
	
SELECT COUNT(1)
INTO V_COUNT
FROM T_RT_LOOKUP
WHERE LOOKUP_DESC = 'DueDateWarningDays';

IF V_COUNT <> 0 THEN
STR_ERR := STR_ERR ||'COUNT IS NOT EQUAL TO 0 KEYS' || CHR(13);  
END IF;

IF (NVL(LENGTH(STR_ERR),
            0) = 0) THEN
        DBMS_OUTPUT.PUT_LINE('ROLLBACK SUCCESSFUL! CURRENT COUNT: ' || V_COUNT || CHR(13));
ELSE
        DBMS_OUTPUT.PUT_LINE('ROLLBACK FAILED! CURRENT COUNT: ' || V_COUNT || CHR(13));
END IF;

END;
/